name: UiPath CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      # 1) 코드를 체크아웃
      - name: Check out repository
        uses: actions/checkout@v2

      # 2) UiPath 사설 피드 설정 (MyGet 예시)
      - name: Configure UiPath Private Feed
        run: |
          dotnet nuget add source "https://www.myget.org/F/uipath-dev/api/v3/index.json" --name UiPathCLI

      # 3) UiPath CLI 설치
      - name: Install UiPath CLI
        run: |
          # 버전을 꼭 지정해야 한다면 --version 추가
          # (23.4.0 은 예시 버전, 현재 최신 버전에 맞춰 수정)
          dotnet tool install --global UiPath.CLI --version 23.4.0 --source "UiPathCLI"

      # 4) CLI PATH 등록
      - name: Add UiPath CLI to PATH
        shell: powershell
        run: echo "$env:USERPROFILE\.dotnet\tools" >> $GITHUB_PATH

      # 5) 설치 확인
      - name: Check UiPath Version
        run: uipath --version

      # 6) Orchestrator 인증
      - name: Authenticate Orchestrator
        run: |
          uipath login \
            --organization-url https://cloud.uipath.com \
            --tenant-name ${{ secrets.UIPATH_TENANT_LOGICAL_NAME }} \
            --client-id ${{ secrets.UIPATH_CLIENT_ID }} \
            --user-key ${{ secrets.UIPATH_USER_KEY }} \
            --account-name ${{ secrets.UIPATH_ACCOUNT_LOGICAL_NAME }}

      # 7) 패키지 생성 & Orchestrator로 배포
      - name: Publish package to Orchestrator
        run: |
          uipath pack --project-path . --output . --version 1.0.$(date +'%Y%m%d%H%M')
          uipath push --orchestrator --feed MyPackages --publish-single
