name: UiPath CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Configure NuGet Feed
        run: |
          dotnet nuget remove source nuget.org || echo "nuget.org not found, skipping removal"
          dotnet nuget remove source "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages" || echo "Local feed not found, skipping removal"
          dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org

      - name: Install UiPath CLI (latest)
        run: |
          dotnet tool install --global UiPath.CLI
          # 특정 버전이 필요하다면:
          # dotnet tool install --global UiPath.CLI --version 24.12.9111.31003 --source "https://api.nuget.org/v3/index.json"

      - name: Add UiPath CLI to PATH
        shell: powershell
        run: echo "$env:USERPROFILE\.dotnet\tools" >> $GITHUB_PATH

      - name: Check UiPath Version
        run: uipath --version

      - name: Authenticate Orchestrator
        run: |
          uipath login \
            --organization-url https://cloud.uipath.com \
            --tenant-name ${{ secrets.UIPATH_TENANT_LOGICAL_NAME }} \
            --client-id ${{ secrets.UIPATH_CLIENT_ID }} \
            --user-key ${{ secrets.UIPATH_USER_KEY }} \
            --account-name ${{ secrets.UIPATH_ACCOUNT_LOGICAL_NAME }}

      - name: Publish package to Orchestrator
        run: |
          uipath pack --project-path . --output . --version 1.0.$(date +'%Y%m%d%H%M')
          uipath push --orchestrator --feed MyPackages --publish-single
