name: UiPath CI/CD
# CICD 테스트
on:
  push:
    branches: [ "main" ]  # 원하는 브랜치명

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      # 1) 코드를 체크아웃
      - name: Check out repository
        uses: actions/checkout@v2

      # 2) NuGet 피드 추가 또는 삭제 후 재등록
      - name: Configure NuGet Feed
        run: |
          dotnet --version  
          dotnet search UiPath.CLI
          dotnet nuget remove source nuget.org || echo "nuget.org not found, skipping removal"
          dotnet nuget add source https://api.nuget.org/v3/index.json --name nuget.org

      # 3) UiPath CLI 설치 (버전 명시)
      - name: Install UiPath CLI
        run: |
          dotnet tool install --global UiPath.CLI --version 24.12.9111.31003
          uipath --version  # 설치 확인

      # 4) UiPath CLI가 PATH에 포함되도록 설정
      - name: Add UiPath CLI to PATH
        run: echo "${{ runner.tool_cache }}/dotnet/tools" >> $GITHUB_PATH

      # 5) Orchestrator에 인증
      - name: Authenticate Orchestrator
        run: |
          uipath login \
            --organization-url https://cloud.uipath.com \
            --tenant-name ${{ secrets.UIPATH_TENANT_LOGICAL_NAME }} \
            --client-id ${{ secrets.UIPATH_CLIENT_ID }} \
            --user-key ${{ secrets.UIPATH_USER_KEY }} \
            --account-name ${{ secrets.UIPATH_ACCOUNT_LOGICAL_NAME }}

      # 6) 패키지 Publish
      - name: Publish package to Orchestrator
        run: |
          uipath --version
          uipath pack --project-path . --output . --version 1.0.$(date +'%Y%m%d%H%M')
          uipath push --orchestrator --feed MyPackages --publish-single
